# Generated by Django 6.0 on 2025-12-13 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.BooleanField(default=True, editable=False, unique=True)),
                ('prompt', models.TextField()),
                ('current_step', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Step 1 - Generation'), (2, 'Step 2 - Selection')], default=0)),
                ('rounds_count', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('llm_generated', 'LLM Generated'), ('user_submitted', 'User Submitted')], default='llm_generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('current_round', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('step_completed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(choices=[(1, 'Step 1 - Generation'), (2, 'Step 2 - Selection')], default=1)),
                ('selected_position', models.IntegerField(blank=True, choices=[(0, 'Left'), (1, 'Right')], null=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rejected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_choices', to='selector.option')),
                ('selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_choices', to='selector.option')),
            ],
        ),
    ]
