# Generated by Django 6.0 on 2025-12-18 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_choices', to='selector.option'),
        ),
    ]
